### ISSUE TITLE
OpenMV Hardware Hacking

### ISSUE THREAD

**Issue by maholli** [spacecraft-design-lab-2019/documentation#12]
Look into OpenMV3 R2 with camera module OV7715-M7

https://github.com/openmv

- [x] design a new PCB based on the OpenMV board, shoot for 35x35mm
- [x] port eagle design to KiCad
- [x] make enable pin accessible to main avionics board (for controlling power to the camera board)

**Comment by maholli** [comment]
STM32 from OpenMV-H7 and OV7725 from OpenMV3 installed on camerav00 board:
![image](https://user-images.githubusercontent.com/29153441/69015144-0ab1b300-0946-11ea-818b-ec5a902a9207.png)

**Comment by NickG-NZ** [comment]
Look awesome.
