### ISSUE TITLE
Deliver Black-Box CircuitPython Module for Burn Wire Testing to Solar/Actuators Team

### ISSUE THREAD

**Issue by ashtofen** [spacecraft-design-lab-2019/documentation#145]
Generate a black box in CircuitPython for members of the solar/actuators team to use to determine the optimal PWM duty cycle and gauge of nichrome wire to use for safe and reliable wire burning.

Find it [here](https://github.com/spacecraft-design-lab-2019/SolarActuators/tree/master) as main.py.

Estimated Completion Date: 11 November 2019
Completed: 11 November 2019

**Comment by maholli** [comment]
@ashtofen make sure to leverage the builtin PWM capabilities :) 

https://learn.adafruit.com/circuitpython-essentials/circuitpython-pwm
