### ISSUE TITLE
H-Bridge Coil Driver Design

### ISSUE THREAD

**Issue by NickG-NZ** [spacecraft-design-lab-2019/documentation#44]
Design coil driver circuits. 
Aim to include on main board.
- [ ]  send Zac H-bridge links to order

**Comment by maholli** [comment]
See H-bridge design on PandaSat as a starting reference (attached). Eagle files will need to be imported into KiCad.
[PandaSat_MB.zip](https://github.com/spacecraft-design-lab-2019/documentation/files/3700173/PandaSat_MB.zip)
