### ISSUE TITLE
Look into SPV1040

### ISSUE THREAD

**Issue by zchen131** [spacecraft-design-lab-2019/documentation#50]
SPV1040 high-efficiency solar battery charger with embedded MPPT

**Comment by thwhite** [comment]
Parts are all added to kicad - prepared to stick it on a board when needed. Have boards to test.

**Comment by thwhite** [comment]
Possibilities - two switching regulators - 5.0V and 6.6V?

**Comment by zchen131** [comment]
Using BQ25570RGRR for PCB design as Max suggested.
