### ISSUE TITLE
Generate +Y Panel step file (3D CAD) - with components

### ISSUE THREAD

**Issue by maholli** [spacecraft-design-lab-2019/documentation#97]
Use google and https://componentsearchengine.com/ to find CAD files for the components

**Comment by maholli** [comment]
Status of this?

**Comment by thwhite** [comment]
Ah, apologies for not updating the issue! @maholli Mechanical has the CAD and it's in the main file right now! I hadn't closed it because it's not aesthetically perfect (e.g. the solar panels are the wrong color).

**Comment by thwhite** [comment]
But can close this issue if it's outstanding.
